# Generated by Django 5.0.4 on 2024-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='materias_logo/'),
        ),
    ]
